server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8083
              predicates:
                - Path=/user-service/v3/api-docs/**, /api/v1/users/**
              filters:
                - RewritePath=/user-service/(?<remaining>.*), /${remaining}
            - id: product-service
              uri: http://localhost:8081
              predicates:
                - Path=/product-service/v3/api-docs/**, /api/v1/products/**
              filters:
                - RewritePath=/product-service/(?<remaining>.*), /${remaining}

            - id: order-service
              uri: http://localhost:8082
              predicates:
                - Path=/order-service/v3/api-docs/**, /api/v1/orders/**
              filters:
                - RewritePath=/order-service/(?<remaining>.*), /${remaining}
springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
      - name: product-service
        url: /product-service/v3/api-docs
      - name: order-service
        url: /order-service/v3/api-docs



          #    autoconfiguration

          #    gateway:
          #      server:
          #        webflux:
          #          discovery:
          #            locator:
          #              enabled: true
          #              lower-case-service-id: true


          #user to filter req,res
          #  - StripPrefix=1
        #  - PrefixPath=/api/v1/users
        #  - RewritePath=/orders/(?<remaining>.*), api/v1/orders/${remaining}



#eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      DefaultZone: http://localhost:8761/eureka/


