spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5444/database_user
    username: seyha
    password: seyha123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



server:
  port: 8083

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/